[[redirects]]
from = "https://voter.netlify.app/*"
to = "https://voter.dk-gl.eu/:splat"
force = true
status = 301

[[redirects]]
from = "/admin/*"
to = "https://voter-admin.dk-gl.eu/admin/:splat"
force = true
status = 200

[[redirects]]
from = "/api/*"
to = "https://voter.karol.gay/api/:splat"
force = true
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
