on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      # https://gist.github.com/guychouk/db0061b989141f55381a66b046adc2c3
      - name: Deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          # -v: verbose
          # -z: compress files during transfer
          # -r: copy files recursively
          # --delete: delete extraneous files from dest dirs
          switches: -vzr --delete
          path: dist/
          remote_path: ${{ vars.DEPLOY_PATH }}
          remote_host: ${{ vars.DEPLOY_HOST }}
          remote_port: ${{ vars.DEPLOY_PORT }}
          remote_user: ${{ vars.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
